/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.vw.preference.center.users.consent.v1;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Consent of a user */
@org.apache.avro.specific.AvroGenerated
public class ConsentUpdateEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6477030301533286764L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"ConsentUpdateEvent\",\"namespace\":\"com.vw.preference.center.users.consent.v1\",\"doc\":\"Consent of a user\",\"fields\":[{\"name\":\"user_id\",\"type\":{\"type\":\"string\",\"avro.java.string\":\"String\"},\"doc\":\"User id\"},{\"name\":\"consent_id\",\"type\":{\"type\":\"enum\",\"name\":\"ConsentIds\",\"doc\":\"Consent id values\",\"symbols\":[\"SMS_NOTIFICATIONS\",\"EMAIL_NOTIFICATIONS\"]}},{\"name\":\"enabled\",\"type\":\"boolean\",\"doc\":\"Indicates whether the consent is enabled\"}],\"subject\":\"preference.center.users.consent.v1.ConsentUpdateEvent\"}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<ConsentUpdateEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<ConsentUpdateEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<ConsentUpdateEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<ConsentUpdateEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<ConsentUpdateEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this ConsentUpdateEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a ConsentUpdateEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a ConsentUpdateEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static ConsentUpdateEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** User id */
  private java.lang.String user_id;
  private com.vw.preference.center.users.consent.v1.ConsentIds consent_id;
  /** Indicates whether the consent is enabled */
  private boolean enabled;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public ConsentUpdateEvent() {}

  /**
   * All-args constructor.
   * @param user_id User id
   * @param consent_id The new value for consent_id
   * @param enabled Indicates whether the consent is enabled
   */
  public ConsentUpdateEvent(java.lang.String user_id, com.vw.preference.center.users.consent.v1.ConsentIds consent_id, java.lang.Boolean enabled) {
    this.user_id = user_id;
    this.consent_id = consent_id;
    this.enabled = enabled;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return user_id;
    case 1: return consent_id;
    case 2: return enabled;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: user_id = value$ != null ? value$.toString() : null; break;
    case 1: consent_id = (com.vw.preference.center.users.consent.v1.ConsentIds)value$; break;
    case 2: enabled = (java.lang.Boolean)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'user_id' field.
   * @return User id
   */
  public java.lang.String getUserId() {
    return user_id;
  }


  /**
   * Sets the value of the 'user_id' field.
   * User id
   * @param value the value to set.
   */
  public void setUserId(java.lang.String value) {
    this.user_id = value;
  }

  /**
   * Gets the value of the 'consent_id' field.
   * @return The value of the 'consent_id' field.
   */
  public com.vw.preference.center.users.consent.v1.ConsentIds getConsentId() {
    return consent_id;
  }


  /**
   * Sets the value of the 'consent_id' field.
   * @param value the value to set.
   */
  public void setConsentId(com.vw.preference.center.users.consent.v1.ConsentIds value) {
    this.consent_id = value;
  }

  /**
   * Gets the value of the 'enabled' field.
   * @return Indicates whether the consent is enabled
   */
  public boolean getEnabled() {
    return enabled;
  }


  /**
   * Sets the value of the 'enabled' field.
   * Indicates whether the consent is enabled
   * @param value the value to set.
   */
  public void setEnabled(boolean value) {
    this.enabled = value;
  }

  /**
   * Creates a new ConsentUpdateEvent RecordBuilder.
   * @return A new ConsentUpdateEvent RecordBuilder
   */
  public static com.vw.preference.center.users.consent.v1.ConsentUpdateEvent.Builder newBuilder() {
    return new com.vw.preference.center.users.consent.v1.ConsentUpdateEvent.Builder();
  }

  /**
   * Creates a new ConsentUpdateEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new ConsentUpdateEvent RecordBuilder
   */
  public static com.vw.preference.center.users.consent.v1.ConsentUpdateEvent.Builder newBuilder(com.vw.preference.center.users.consent.v1.ConsentUpdateEvent.Builder other) {
    if (other == null) {
      return new com.vw.preference.center.users.consent.v1.ConsentUpdateEvent.Builder();
    } else {
      return new com.vw.preference.center.users.consent.v1.ConsentUpdateEvent.Builder(other);
    }
  }

  /**
   * Creates a new ConsentUpdateEvent RecordBuilder by copying an existing ConsentUpdateEvent instance.
   * @param other The existing instance to copy.
   * @return A new ConsentUpdateEvent RecordBuilder
   */
  public static com.vw.preference.center.users.consent.v1.ConsentUpdateEvent.Builder newBuilder(com.vw.preference.center.users.consent.v1.ConsentUpdateEvent other) {
    if (other == null) {
      return new com.vw.preference.center.users.consent.v1.ConsentUpdateEvent.Builder();
    } else {
      return new com.vw.preference.center.users.consent.v1.ConsentUpdateEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for ConsentUpdateEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<ConsentUpdateEvent>
    implements org.apache.avro.data.RecordBuilder<ConsentUpdateEvent> {

    /** User id */
    private java.lang.String user_id;
    private com.vw.preference.center.users.consent.v1.ConsentIds consent_id;
    /** Indicates whether the consent is enabled */
    private boolean enabled;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.vw.preference.center.users.consent.v1.ConsentUpdateEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.user_id)) {
        this.user_id = data().deepCopy(fields()[0].schema(), other.user_id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.consent_id)) {
        this.consent_id = data().deepCopy(fields()[1].schema(), other.consent_id);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.enabled)) {
        this.enabled = data().deepCopy(fields()[2].schema(), other.enabled);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing ConsentUpdateEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.vw.preference.center.users.consent.v1.ConsentUpdateEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.user_id)) {
        this.user_id = data().deepCopy(fields()[0].schema(), other.user_id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.consent_id)) {
        this.consent_id = data().deepCopy(fields()[1].schema(), other.consent_id);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.enabled)) {
        this.enabled = data().deepCopy(fields()[2].schema(), other.enabled);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'user_id' field.
      * User id
      * @return The value.
      */
    public java.lang.String getUserId() {
      return user_id;
    }


    /**
      * Sets the value of the 'user_id' field.
      * User id
      * @param value The value of 'user_id'.
      * @return This builder.
      */
    public com.vw.preference.center.users.consent.v1.ConsentUpdateEvent.Builder setUserId(java.lang.String value) {
      validate(fields()[0], value);
      this.user_id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'user_id' field has been set.
      * User id
      * @return True if the 'user_id' field has been set, false otherwise.
      */
    public boolean hasUserId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'user_id' field.
      * User id
      * @return This builder.
      */
    public com.vw.preference.center.users.consent.v1.ConsentUpdateEvent.Builder clearUserId() {
      user_id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'consent_id' field.
      * @return The value.
      */
    public com.vw.preference.center.users.consent.v1.ConsentIds getConsentId() {
      return consent_id;
    }


    /**
      * Sets the value of the 'consent_id' field.
      * @param value The value of 'consent_id'.
      * @return This builder.
      */
    public com.vw.preference.center.users.consent.v1.ConsentUpdateEvent.Builder setConsentId(com.vw.preference.center.users.consent.v1.ConsentIds value) {
      validate(fields()[1], value);
      this.consent_id = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'consent_id' field has been set.
      * @return True if the 'consent_id' field has been set, false otherwise.
      */
    public boolean hasConsentId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'consent_id' field.
      * @return This builder.
      */
    public com.vw.preference.center.users.consent.v1.ConsentUpdateEvent.Builder clearConsentId() {
      consent_id = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'enabled' field.
      * Indicates whether the consent is enabled
      * @return The value.
      */
    public boolean getEnabled() {
      return enabled;
    }


    /**
      * Sets the value of the 'enabled' field.
      * Indicates whether the consent is enabled
      * @param value The value of 'enabled'.
      * @return This builder.
      */
    public com.vw.preference.center.users.consent.v1.ConsentUpdateEvent.Builder setEnabled(boolean value) {
      validate(fields()[2], value);
      this.enabled = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'enabled' field has been set.
      * Indicates whether the consent is enabled
      * @return True if the 'enabled' field has been set, false otherwise.
      */
    public boolean hasEnabled() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'enabled' field.
      * Indicates whether the consent is enabled
      * @return This builder.
      */
    public com.vw.preference.center.users.consent.v1.ConsentUpdateEvent.Builder clearEnabled() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public ConsentUpdateEvent build() {
      try {
        ConsentUpdateEvent record = new ConsentUpdateEvent();
        record.user_id = fieldSetFlags()[0] ? this.user_id : (java.lang.String) defaultValue(fields()[0]);
        record.consent_id = fieldSetFlags()[1] ? this.consent_id : (com.vw.preference.center.users.consent.v1.ConsentIds) defaultValue(fields()[1]);
        record.enabled = fieldSetFlags()[2] ? this.enabled : (java.lang.Boolean) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<ConsentUpdateEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<ConsentUpdateEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<ConsentUpdateEvent>
    READER$ = (org.apache.avro.io.DatumReader<ConsentUpdateEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.user_id);

    out.writeEnum(this.consent_id.ordinal());

    out.writeBoolean(this.enabled);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.user_id = in.readString();

      this.consent_id = com.vw.preference.center.users.consent.v1.ConsentIds.values()[in.readEnum()];

      this.enabled = in.readBoolean();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.user_id = in.readString();
          break;

        case 1:
          this.consent_id = com.vw.preference.center.users.consent.v1.ConsentIds.values()[in.readEnum()];
          break;

        case 2:
          this.enabled = in.readBoolean();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










