/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.vw.preference.center.users.consent.v1;
/** Consent id values */
@org.apache.avro.specific.AvroGenerated
public enum ConsentIds implements org.apache.avro.generic.GenericEnumSymbol<ConsentIds> {
  SMS_NOTIFICATIONS, EMAIL_NOTIFICATIONS  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"ConsentIds\",\"namespace\":\"com.vw.preference.center.users.consent.v1\",\"doc\":\"Consent id values\",\"symbols\":[\"SMS_NOTIFICATIONS\",\"EMAIL_NOTIFICATIONS\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
